export const USER_CLASS_THEME = {
  GUERRERO: {
    label: "Guerrero",
    labelShort: "GUERRERO",
    title: "Camino de fuerza",
    accent: "#ff4d5e",
    secondary: "#c9184a",
    bg: "#21070d",
    soft: "rgba(255, 77, 94, .2)",
    crest: "/ui/crest-warrior.png",
    sprite: "/home_guerrero/home_idle_guerrero_01.png",
    stat: "Fuerza",
    focusZones: ["fuerza"],
  },
  ARQUERO: {
    label: "Arquero",
    labelShort: "ARQUERO",
    title: "Ritmo y precision",
    accent: "#7bdc3b",
    secondary: "#20c997",
    bg: "#061f16",
    soft: "rgba(123, 220, 59, .18)",
    crest: "/ui/crest-archer.png",
    sprite: "/home_arquero/home_idle_arquero_01.png",
    stat: "Agilidad",
    focusZones: ["cardio", "nutricion"],
  },
  MAGO: {
    label: "Mago",
    labelShort: "MAGO",
    title: "Dominio mental",
    accent: "#4cc9f0",
    secondary: "#2f80ed",
    bg: "#06182d",
    soft: "rgba(76, 201, 240, .18)",
    crest: "/ui/crest-mage.png",
    sprite: "/home_mago/home_idle_mago_01.png",
    stat: "Vitalidad",
    focusZones: ["mente", "flexibilidad"],
  },
  DEFAULT: {
    label: "Aventurero",
    labelShort: "AVENTURA",
    title: "Forja personal",
    accent: "#c08aff",
    secondary: "#c08aff",
    bg: "#12091f",
    soft: "rgba(192, 138, 255, .15)",
    crest: "/ui/crest-default.png",
    sprite: "/avatar/idle/idle_01.png",
    stat: "Balance",
    focusZones: ["mision"],
  },
};
