// src/avatar/AvatarCatalog.js
// Catálogo de avatares de perfil y marcos circulares.
// Imágenes en /public/perfil/avatar_01.png … avatar_10.png

export const getAvatarImage = (id) => `/perfil/${id}.png`;

export const AVATARS_CATALOG = [
  {
    id:      "avatar_01",
    nombre:  "Héroe Clásico",
    desc:    "El avatar por defecto de todo aventurero en ForgeVenture.",
    precio:  0,
    rareza:  "Común",
    color:   "#C9184A",
    esNuevo: false,
  },
  {
    id:      "avatar_02",
    nombre:  "Alma de Fuego",
    desc:    "Imparable, ardiente y poderoso. Para los que nunca se rinden.",
    precio:  400,
    rareza:  "Común",
    color:   "#FF4D6D",
    esNuevo: true,
  },
  {
    id:      "avatar_03",
    nombre:  "Espíritu Ártico",
    desc:    "Frío, calculador e implacable. La mente sobre el músculo.",
    precio:  400,
    rareza:  "Común",
    color:   "#4CC9F0",
    esNuevo: true,
  },
  {
    id:      "avatar_04",
    nombre:  "Rayo Veloz",
    desc:    "Velocidad y potencia en un solo avatar. El más rápido del reino.",
    precio:  800,
    rareza:  "Poco común",
    color:   "#818CF8",
    esNuevo: true,
  },
  {
    id:      "avatar_05",
    nombre:  "Lobo Solitario",
    desc:    "Disciplinado, feroz y sin igual. Nunca caza en grupo.",
    precio:  1200,
    rareza:  "Raro",
    color:   "#9CA3AF",
    esNuevo: true,
  },
  {
    id:      "avatar_06",
    nombre:  "Dragón Ascendido",
    desc:    "El poder del dragón fluye en tus venas. Respeto instantáneo.",
    precio:  2000,
    rareza:  "Épico",
    color:   "#F97316",
    esNuevo: true,
  },
  {
    id:      "avatar_07",
    nombre:  "Fénix Eterno",
    desc:    "Renace más fuerte después de cada caída. La cima de la leyenda.",
    precio:  3500,
    rareza:  "Legendario",
    color:   "#FFB4A2",
    esNuevo: true,
  },
  {
    id:      "avatar_08",
    nombre:  "Sombra Oscura",
    desc:    "Sigiloso y letal. Opera en las sombras, golpea en la luz.",
    precio:  1500,
    rareza:  "Raro",
    color:   "#7B2FBE",
    esNuevo: true,
  },
  {
    id:      "avatar_09",
    nombre:  "Tormenta Solar",
    desc:    "Energía pura canalizada. Donde él pasa, la tormenta queda.",
    precio:  2500,
    rareza:  "Épico",
    color:   "#FFD700",
    esNuevo: true,
  },
  {
    id:      "avatar_10",
    nombre:  "Campeón Supremo",
    desc:    "Solo uno puede serlo. El máximo honor de ForgeVenture.",
    precio:  5000,
    rareza:  "Legendario",
    color:   "#C9184A",
    esNuevo: true,
  },
];

export const FRAMES_CATALOG = [
  {
    id:        "marco_01",
    nombre:    "Marco Carmesí",
    desc:      "Un anillo de fuego carmesí. Elegancia y peligro en uno.",
    precio:    600,
    rareza:    "Común",
    color:     "#C9184A",
    gradient:  "linear-gradient(135deg,#C9184A,#FF4D6D,#7A1E3D,#C9184A)",
    animated:  false,
    esNuevo:   true,
  },
  {
    id:        "marco_02",
    nombre:    "Marco Dorado",
    desc:      "El brillo del oro para los verdaderos campeones.",
    precio:    800,
    rareza:    "Poco común",
    color:     "#FFC857",
    gradient:  "linear-gradient(135deg,#FFC857,#FFD700,#B8860B,#FFC857)",
    animated:  false,
    esNuevo:   true,
  },
  {
    id:        "marco_03",
    nombre:    "Marco Élite Azul",
    desc:      "Eléctrico y veloz. Para el arquero que todo lo alcanza.",
    precio:    800,
    rareza:    "Poco común",
    color:     "#4CC9F0",
    gradient:  "linear-gradient(135deg,#4CC9F0,#0096C7,#023E8A,#4CC9F0)",
    animated:  false,
    esNuevo:   true,
  },
  {
    id:        "marco_04",
    nombre:    "Marco del Vacío",
    desc:      "Oscuro y misterioso. Solo los más valientes lo portan.",
    precio:    1500,
    rareza:    "Raro",
    color:     "#7B2FBE",
    gradient:  "linear-gradient(135deg,#7B2FBE,#2D1B69,#5B21B6,#7B2FBE)",
    animated:  false,
    esNuevo:   true,
  },
  {
    id:        "marco_05",
    nombre:    "Marco Arcoíris",
    desc:      "Vibrante, imposible de ignorar. Gira sin parar.",
    precio:    2500,
    rareza:    "Épico",
    color:     "#FF6B6B",
    gradient:  "conic-gradient(from 0deg,#FF6B6B,#FFD93D,#6BCB77,#4D96FF,#C77DFF,#FF6B6B)",
    animated:  true,
    esNuevo:   true,
  },
  {
    id:        "marco_06",
    nombre:    "Marco Leyenda",
    desc:      "Solo para los más grandes héroes de ForgeVenture. Inigualable.",
    precio:    5000,
    rareza:    "Legendario",
    color:     "#FFC857",
    gradient:  "conic-gradient(from 0deg,#FFC857,#C9184A,#4CC9F0,#C77DFF,#FFC857)",
    animated:  true,
    esNuevo:   true,
  },
];

export const RAREZA_AVATAR_COLOR = {
  "Común":       "#A08090",
  "Poco común":  "#4ADE80",
  "Raro":        "#4CC9F0",
  "Épico":       "#9B5DE5",
  "Legendario":  "#FFC857",
};
